language: php

php:
  - 5.4
  - 5.5
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
  include:
    - php: 5.6
      env: PHPUNIT_FLAGS="--coverage-clover coverage.clover" CHECK_CS=true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - if [[ "$CHECK_CS" != "" ]]; then vendor/bin/symplify-cs check src tests; fi

after_script:
- if [[ "$PHPUNIT_FLAGS" != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
